name: singularity
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  carousel_slider: ^5.1.1
  connectivity_plus: ^7.0.0
  file_picker: ^10.3.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  google_fonts: ^6.3.2
  image_picker: ^1.2.1
  supabase: ^2.10.0
  supabase_flutter: ^2.10.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter_native_splash:
  color: "#19A7CE" # Warna background 
  image: "assets/images/splash_screen.png"
  android_12: 
    image: "assets/images/splash_screen.png"
    color: "#19A7CE"
  fullscreen: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # Opsional

flutter:
  uses-material-design: true
  assets:
    - assets/images/
